### ISSUE TITLE
Hi, where to get the training data

### ISSUE THREAD

**Issue by CountofMont** [VCL3D/DeepDepthDenoising#1]

**Comment by tofis** [comment]
Hello @CountofMont and thank you for your interest to our repo. The dataset used for training our model is not publicly available, however we used the [VolumetricCapture](https://github.com/VCL3D/VolumetricCapture) tools and the dataset structure shown in [dataloader.py](https://github.com/VCL3D/DeepDepthDenoising/blob/master/dataset/dataloader.py). To this end, you will be able to easily capture multi-view RGBD data for your purpose. Hope these help.
