### ISSUE TITLE
Interiornet Dataset (Noise)

### ISSUE THREAD

**Issue by AkbarShah96** [VCL3D/DeepDepthDenoising#2]
Hey guys, great work you have here and thank you for providing the code. I would just like to ask if you could upload the scripts that you use for adding artificial noise to Interiornet dataset so that other researchers are able to benefit from your work.

I would be very grateful if you could do it as soon as possible!

Thank you!

**Comment by zuru** [comment]
Hi,

you can find the noise functions in `evaluation/noise.py` and the InteriorNet script at `add_noise_interiornet.py` along with some default values that we used.

**Comment by AkbarShah96** [comment]
Hey,

Thanks for the code.

I would like to ask if the reported results were evaluated on a test split from within the first 300 scenes or was it tested on other scenes?

Could you also share which scene was Figure 11 in the paper taken from since there are millions of images within the dataset? :) 

Thank you!
