### ISSUE TITLE
Interiornet ( Test split, example image)

### ISSUE THREAD

**Issue by AkbarShah96** [VCL3D/DeepDepthDenoising#3]
Hey,

Thanks for the code.

I would like to ask if the reported results were evaluated on a test split from within the first 300 interior net scenes or was it tested on other scenes?

Could you also share which scene was Figure 11 in the paper taken from since there are millions of images within the dataset? :)

Thank you!

**Comment by tofis** [comment]
Hello @AkbarShah96,

What we did is that we took the first 20 samples per scene from the first 300 scenes of the InteriorNet dataset, we artificially added noise to them, as reported in the supplementary material of the paper, and then we denoised them using our model trained on the balloon-human dataset we created using a [multi-view RGBD capture system](https://github.com/VCL3D/VolumetricCapture).

With respect to the scenes and samples in Figure 11, the scenes and sample ids are:

- 3FO4IERA6E41_Living_room_Sample#15
- 3FO4IFC5UYLB_Kitchen_Sample#5
- 3FO4IDGMDQA4_Dining_room_Sample#6
- 3FO4IF4VQF87_Study_Sample#0

I hope now it's clear and you can reproduce the results.
