### ISSUE TITLE
Weight Load

### ISSUE THREAD

**Issue by jinseok-karl** [VCL3D/DeepDepthDenoising#6]
Hi, first of all, thanks for your sharing this great code.
I'd like to follow the code. But, I couldn't understand the pretrained weight format.
You loaded the 6files, 
ddd
DeepDepthDenoising-ddd.tar.gz
DeepDepthDenoising-ddd.zip
ddd_ae
DeepDepthDenoising-ddd_ae.tar.gz
DeepDepthDenoising-ddd_ae.zip
But I don't know the format ddd and ddd_ae.
And Which one is the weight that that I have to torch.load?
Sorry for easy one. But I'd like you to tell me.
Thanks.

**Comment by vladsterz** [comment]
Hello @jinseok-karl ,
hope you find our work insightful for your own purposes.
Correct me if I did not understand you correctly, but you want to see how do we load our pre-trained models?
If so, first of all you should not care about the _tar.gz_ and _zip_ files, they are uploaded automatically by github, you care only about _ddd_ and _ddd_ae_ files, which are indeed the pretrained weights for 2 distinct models, as stated in our [home page](https://github.com/VCL3D/DeepDepthDenoising#inference).
If you want to load the models in your code, please refer to [this function](https://github.com/VCL3D/DeepDepthDenoising/blob/78851c9bf5c41a83cafbe0cb3f2d37af97718035/utils/init.py#L6) which initializes a model and be sure to have the correct model, which is created by [this function](https://github.com/VCL3D/DeepDepthDenoising/blob/78851c9bf5c41a83cafbe0cb3f2d37af97718035/models/__init__.py#L5).
For any other use case, please refer to our [inference script](https://github.com/VCL3D/DeepDepthDenoising/blob/master/inference.py) and the documentation on our main page.
For any further questions please do not hesitate to ask us.

**Comment by jinseok-karl** [comment]
Oh! Thanks, Only problem is that there is no weight I think!
But ddd,ddd_ae was weight! I thought the torch weight always has the pth, pth.tar format.
Since there is no filename extension, So I never know that.
Thanks!
